FROM rocker/verse:4.3.0
RUN apt-get update -y && apt-get install -y  libicu-dev make pandoc  libcurl4-openssl-dev libssl-dev libnode-dev  libicu-dev  make  cmake make libicu-dev  libcurl4-openssl-dev libssl-dev  zlib1g-dev  make zlib1g-dev  libicu-dev libcurl4-openssl-dev libssl-dev libnode-dev make libxml2-dev pandoc  pandoc  cmake make  libssl-dev  libicu-dev libcurl4-openssl-dev libssl-dev zlib1g-dev make pandoc  git  libxml2-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
